name: article-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - azure-functions=1.19.0
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-surprise=1.1.4
  - scipy=1.15.2
  - joblib=1.5.1
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pip=25.1
  - setuptools=78.1.1
  - wheel=0.45.1
  - tzdata=2025b
