name: article-recommender
channels:
  - conda-forge
  - defaults
dependencies:
  - azure-functions=1.19.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - intel-openmp=2024.2.1
  - joblib=1.5.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - mkl=2024.2.2
  - numpy=1.26.4
  - openssl=3.5.0
  - pandas=2.2.3
  - pip=25.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytz=2025.2
  - scikit-surprise=1.1.4
  - scipy=1.15.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.13.0
  - tk=8.6.14
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
