name: Build and deploy Python project to Azure Function App - article-recommender-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."
  PYTHON_VERSION: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash -el {0} # Nécessaire pour l'activation Conda

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          activate-environment: article-recommender
          environment-file: environment.yml
          use-only-tar-bz2: true # Important pour le caching
          auto-activate-base: false

      - name: Install dependencies with Conda
        run: |
          conda update --all -y
          conda env update -n article-recommender -f environment.yml

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x '*.git*' -x '*.venv*' -x '*.conda*'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: "article-recommender-api"
          slot-name: "Production"
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D6F651A8C4F4B4FA249EB5B1C501CCA }}
